= Web Startup for Class
:big-screen: https://github.com/Tertle950/startup-for-class/blob/main/big-screen-mockup.png?raw=true
:phone-screen: https://github.com/Tertle950/startup-for-class/blob/main/phone-screen-mockup.png?raw=true

== Elevator Pitch
You have a problem with a lot of potential solutions, and a lot of
people/friends/colleagues want to pitch ideas to you at once. This
website allows all of them to pitch in ideas with their phones
from (a different page on) the same website, using a "host code"
system similar to Among Us and Jackbox Party Pack games.

Afterward, pick any one idea you like the most...or, if you're
still undecided, pick more than one idea and put it up to a vote.

image::{big-screen}[alt=Mockup of website design on the host side,width=900,float="right"]
image::{phone-screen}[alt=Mockup of website design on the suggester's side,width=450,float="right"]

== Technologies represented in this deliverable so far...
游댮 Not implemented yet. +
游리 In progress. +
游릭 Fully implemented! :D

- HTML
** 游릭 Each component of the application has an HTML page.
** 游릭 Proper use of HTML tags.
** 游릭 Links between pages
** 游릭 Application textual content
** 游릭 Placeholder for 3rd party service calls in Profile page for themes.
** 游릭 Application images.
** 游릭 Login placeholder.
** 游릭 Database data placeholder.
** 游릭 WebSocket placeholder.
- CSS
** 游리 Bootstrap!
** 游릭 Properly styled header and footer
** 游릭 Responsive to window sizing (yeah, that's Bootstrap)
** 游리 Properly styled application elements (there's a particularly tricky one in profile.html)
** 游리 Properly styled text content (host page doesn't quite match the mockup yet)
** 游리 Properly styled images
- JavaScript
** 游댮 Login placeholder
** 游댮 Database placeholder (requires login first!)
** 游릭 WebSocket placeholder
** 游리 Interaction logic placeholder
